apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-email-alert
  namespace: monitoring
spec:
  groups:
  - name: test.rules
    rules:
    - alert: TestEmailAlert
      expr: vector(1)
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Yahoo Email Alert Test"
        description: "This confirms Yahoo SMTP is working"
